### ISSUE TITLE
Compute and cache the burn-in period

### ISSUE THREAD

**Issue by gaperez64** [gaperez64/regvsjax#3]
It's a good idea to copy the `sim.py` script and change it to generate a csv with the state of the system after the burn-in period.

**Comment by rgnmnl** [comment]
I just checked your afterburnin.csv file against mine and we are getting quite substantial mismatches. Do you have a copy of your burn in cache so I can compare the other years?

**Comment by gaperez64** [comment]
I did not cache anything in computing that csv file. However, I just pushed (to the same branch) a cleaned version of sim.py which we can use to visualize (see below) and cache the data for some part of the simulation. Perhaps it is good if you graph the (aggregated) lines of the dynamics so that we select some dates to dump and compare?

![graph-before-burnin](https://github.com/user-attachments/assets/e1587d40-d9e7-48a7-a495-6f3f9f509a62)

**Comment by rgnmnl** [comment]
It's really hard to tell with the aggregates because our plots look identical. 
![plot_compartments_2024nov18](https://github.com/user-attachments/assets/cb218257-5f6b-4bdf-989e-72ce20b83866)

But when comparing your Expose and Infected compartments in afterburnin.csv, we see these differences, which are not present (or present in a miniscule scale) for the S, R, and V compartments:
![plot_EvsI_2024nov18](https://github.com/user-attachments/assets/5b8fd059-ad9b-4c40-9119-5327d23da563)

**Comment by rgnmnl** [comment]
Based on burn.py, I took the compartment counts at the end of day 2191. Looks like the plot matches up better.

![plot_endday2191](https://github.com/user-attachments/assets/c1ee79f7-695b-4010-b00f-7c53f28e6f6e)

Still some differences though (in S and R compartment) and I can't quite pinpoint the source.

**Comment by gaperez64** [comment]
I modified `test.py` to check for every compartment differences in our values up to a tolerance of 100 and found none in the 2-year period we were using to test before. It did not find anything (so such differences pop up later?).

If you extend the data dump from 2019-1-1 to add 2 more years, I can rerun it and see what comes up.

**Comment by gaperez64** [comment]
> Based on burn.py, I took the compartment counts at the end of day 2191. Looks like the plot matches up better.
> 
> ![plot_endday2191](https://private-user-images.githubusercontent.com/44297859/387264877-c1ee79f7-695b-4010-b00f-7c53f28e6f6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDc0MTgsIm5iZiI6MTczMTk0NzExOCwicGF0aCI6Ii80NDI5Nzg1OS8zODcyNjQ4NzctYzFlZTc5ZjctNjk1Yi00MDEwLWIwMGYtN2M1M2YyOGU2ZjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDE2MjUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZjZhNTE4NDIxODM5MmFhOTEyZDc2MjFhYzI1OTkzOGY4ZmVlYTEyZTA3N2E0MjliMGI2ZGE3NmE4NjIxMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NxUVdWEQfcJc-m8yo3kMmuYvPtqDWlVDWgPD6HiP1Fs)
> 
> Still some differences though (in S and R compartment) and I can't quite pinpoint the source.

Is it your data or mine that has people concentrated on a small group of ages?
